@isTest
private class EmailManagerUnderReviewTest {
    /*


    
      static testMethod void testListsPost() {
      	PostUnderReviewStatusDaily postreview = new PostUnderReviewStatusDaily();
        Test.startTest();
		List<Posts__c> mypost = [SELECT Id, Name,Status__c,Writer__c,CreatedById
                    FROM Posts__c
                    WHERE Status__c = 'Under Review'];
		Integer cont=0;
        for(Posts__c i: mypost){
        	String ident=mypost[cont].CreatedById;
            cont++;
            
     
    			
        }
        Test.stopTest();
        System.debug('Im Here!');
        System.assertEquals(4, cont);
      }
}*/

}